### ISSUE TITLE
Lock orientation portrait not working! ( iOS 9.x , Android 5.x )

### ISSUE THREAD

**Issue by TawabG** [gbenvenuti/cordova-plugin-screen-orientation#100]
So I'm working with the intel XDK IDE and I've installed this plugin.
I want to keep my app locked in portrait, but for some reason when I rotate my phone the screen starts rotating too, thus ignoring this plugin completely.

Is there any way to fix it? or do I just have to accept this and move on..?

**Comment by jamie49** [comment]
I've also been experiencing similar issues with iOS 9.3, screen.lockOrientation("landscape") doesn't seem to lock the screen anymore.

The only way I can achieve this is by modifying the Deployment settings within xCode (setting orientation to landscape under Device Orientation), but then I can't use the plugin to lock/unlock like I used to... it will always stay landscape.

**Comment by JahBrewski** [comment]
Same here. Appears to be broken in 9.3.

**Comment by jamie49** [comment]
It looks like the plugin creator is aware of the issue.

[bug link](https://github.com/gbenvenuti/cordova-plugin-screen-orientation/issues/84)

"In testing I was able to switch the orientation with the below, however have not been able to lock it to that orientation yet. I will continue to investigate as I have time but as always, pull requests welcome."

**Comment by benmcmaster** [comment]
Yep broken for me in iOS 9.3.1 on my iPhone. My iPad has 9.2 and it seems to be working fine.

I have 
```<preference name="orientation" value="portrait" />```

I want to unlock this for tablets in my universal app. But when I add the plugin it will unlock the orientation change iPhone 9.3 no matter what. Too bad. I would love to unlock portrait orientation for iPads and Android Tablets.

**Comment by benmcmaster** [comment]
It seems that this plugin unlocks the orientation regardless of the preference listed in the config.xml file.

Setting ```window.screen.lockOrientation('portrait')``` in ```onDeviceReady()``` solved my issue.

**Comment by Vahn84** [comment]
hi, i see that you've managed to make it work

but for me in iOS is still broken

i've coded a function inside the $rootScope.on("$stateChangeSuccess.... to lock the screen in landscape when a certain view gets called. Android works as expected...ios ignores it completely

**Comment by benmcmaster** [comment]
Please ask this publicly in the thread. Include your config and relevant code. Your question might help someone else.

**Comment by tony--** [comment]
@TawabG - @gbenvenuti has released 1.4.2 which should fix at least the iOS part of this issue. Will you try 1.4.2 and provide an update, please?

**Comment by rbarriuso** [comment]
v1.4.2 works on iPhone 5s with iOS 9.3.2

**Comment by tony--** [comment]
@rbarriuso - thanks for the confirmation, I'll close this as resolved.
OP or other commenters - please provide additional feedback if this issue is not resolved for you.
