### ISSUE TITLE
Uncaught TypeError: window.screen.lockOrientation is not a function

### ISSUE THREAD

**Issue by braianj** [gbenvenuti/cordova-plugin-screen-orientation#105]
Hello,
I read a lot about this, I tried 
`screen.lockOrientation('landscape');` 
and also
`window.screen.lockOrientation('landscape');`
and if I make  unlock it return me the same.

window.screen return this:
`Screen {}
availHeight: 640
availLeft: 0
availTop: 0
availWidth: 360
colorDepth: 32
height: 640
orientation: ScreenOrientation
angle: 0
onchange: null
type: "portrait-primary"
__proto__: ScreenOrientation
pixelDepth: 32`

$ ionic info
Your system information:
Cordova CLI: 6.0.0
Ionic Version: 1.0.1
Ionic CLI Version: 2.0.0-beta.22
Ionic App Lib Version: 2.0.0-beta.12
ios-deploy version: 1.8.2 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v5.9.0
Xcode version: Xcode 7.3 Build version 7D175 

$ ionic plugin ls
com.ionic.deploy 0.2.3 "IonicDeploy"
cordova-plugin-console 1.0.1 "Console"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-inappbrowser 1.2.1 "InAppBrowser"
cordova-plugin-screen-orientation 1.4.0 "Screen Orientation"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.2 "StatusBar"
cordova-plugin-whitelist 1.0.0 "Whitelist"
ionic-plugin-keyboard 2.0.1 "Keyboard"

I have reinstalled several times the plugin. Removed and add again the platform.
Any idea?

**Comment by tony--** [comment]
@braianj - My guess is that your code is trying to access that API before the module has been loaded.  In a Cordova application you need to wait for the `deviceready` event to be fired.  [The Ionic equivalent is platform.ready](http://ionicframework.com/docs/ionic-cli-faq/#platform-ready).  If you move your code into a ready listener, do you still get this error?

**Comment by braianj** [comment]
Hello @tony--, i I've found this. In index.html I added the next line:
`<script> window.cordova = {} </script>`
This line solve a problem on ios that shows a white screen when input is selected, but if I add it, the orientation plugin crash.
So the solution for this problem was delete that line.
Thanks anyway
