### ISSUE TITLE
on iOS，Why is performed twice？

### ISSUE THREAD

**Issue by llw** [gbenvenuti/cordova-plugin-screen-orientation#106]
on iOS， I tried ：
screen.lockOrientation('landscape'); 

but return this：
2016-05-06 17:52:00.301 TPortalApp[8065:267914] app:Orientation is landscape
2016-05-06 17:52:00.301 TPortalApp[8065:267914] app:Orientation is portrait-primary

Why is performed twice？

**Comment by tony--** [comment]
@llw - I'm guessing that those log messages are coming from and `orientationchange` event listener?  I tried to reproduce this but am not seeing multiple events on an iPhone 6 running 9.3.1.  Can you provide some sample code that shows how to reproduce this issue?

**Comment by tony--** [comment]
No response in over a week and AFAIK this issue is resolved so I'm going to close this.
OP please provide additional feedback if this issue is not resolved for you.
