### ISSUE TITLE
Plugin gets ignored in iOS 9.3.1

### ISSUE THREAD

**Issue by Vahn84** [gbenvenuti/cordova-plugin-screen-orientation#108]
hi, i see that someone has been able to make it work

but for me in iOS  9.3.1 is still broken

i've coded a function inside the $rootScope.on("$stateChangeSuccess.... to lock the screen in landscape when a certain view gets called. Android works as expected...ios ignores it completely

**Comment by ivanovevgeny** [comment]
I have the same issue on iOS.
`if (window.isTablet) {
    console.log('is Tablet, unlock orientation');
    screen.unlockOrientation();
} else {
   console.log('is Phone, lock portrait orientation');
   screen.lockOrientation('portrait');
} `

Output:
>  console.log('is Phone, lock portrait orientation');

Despite this, I can change the screen orientation. Tested on iphone 5s, iphone 6s plus (both 9.3.1).

**Comment by ivanovevgeny** [comment]
@tony--  PR works. 
cordova plugin add https://github.com/tony--/cordova-plugin-screen-orientation#fix-ios-rotate-on-lock

**Comment by tony--** [comment]
@Vahn84 - @gbenvenuti has released 1.4.2 which should fix this issue.  Will you try 1.4.2 and provide an update, please?

**Comment by Vahn84** [comment]
Hi, thank you for the advice. I'll let you know asap

**Comment by Vahn84** [comment]
I can confirm the v1.4.2 has solved the issue
Thanks for the effort!
