### ISSUE TITLE
on iOS: unlockOrientation() not working

### ISSUE THREAD

**Issue by AbraXus** [gbenvenuti/cordova-plugin-screen-orientation#111]
Hey all,
unlockOrientation() seems to be broken on iOS. 

**Expected:** 
When I call `screen.unlockOrientation()` and then tilt the phone, the rotation should change freely. 

**Observed:** 
Rotation doesn't change when tilting phone, orientation is not unlocked. 

The functionality works like that on Android. 
**Note:** Calling `screen.lockOrientation("landscape")` or `screen.lockOrientation("portrait")` works after the last plugin update (1.4.2).

Cordova Version: 6.1.1 
iOS Version: 9.3.2
Plugin Version: 1.4.2

Any help would be much appreciated.

**Comment by tony--** [comment]
@AbraXus - In the current implementation, `screen.unlockOrientation` resets the orientation to match the default.  If you want to have free rotation on iOS you can set the Orientation preference to `all`.
Add the following to the iOS platform section of config.xml:
`<preference name="Orientation" value="all"/>`

**Comment by AbraXus** [comment]
@tony-- Thanks a lot for the tip! It's working as expected now.
