### ISSUE TITLE
Doesn't work on Android 6

### ISSUE THREAD

**Issue by vukasin0** [gbenvenuti/cordova-plugin-screen-orientation#112]
Is this tested on Android 6 ?

Currently this works as expected on Android 5.x but not on 6.

**Comment by tony--** [comment]
@vukasin0 - thanks for opening the issue.  Currently we are migrating to Apache Cordova JIRA so I migrated your issue to [CB-11363](https://issues.apache.org/jira/browse/CB-11363)
