### ISSUE TITLE
iOS 9.3.2 keeps screen orientation locked

### ISSUE THREAD

**Issue by vukasin0** [gbenvenuti/cordova-plugin-screen-orientation#113]
It seems that unlock doesn't do the job. On login page I'm locking with:
```
window.screen.lockOrientation('portrait');
```

and once successful login I changed to default page where I unlock orientation:
```
window.screen.unlockOrientation() 
```

**Comment by tony--** [comment]
@vukasin0 - `unlockOrientation` unlocks the orientation lock set by this plugin.  It sounds like you want to lock orientation to portrait and then allow any orientation.  In order for this to work you would need to set the orientation preference to all.  Please refer to #111
