### ISSUE TITLE
IOS, @media orientation doesn't change

### ISSUE THREAD

**Issue by furuihe** [gbenvenuti/cordova-plugin-screen-orientation#116]
I'm using Cordova v6.1.1, ios 9.2.1
I change screen orientation by calling `screen.lockOrientation('landscape')`
the app change screen orientation, but sometimes app width stays as in portrait mode, and i found that @media orientation is still portrait

**Comment by tony--** [comment]
@furuihe thanks for the report.
This repository is no longer being maintained ([see README for more information](https://github.com/gbenvenuti/cordova-plugin-screen-orientation/blob/master/README.md)).
Please log an issue in [Apache Cordova JIRA for the "Plugin Screen Orientation" component](https://issues.apache.org/jira/browse/CB/component/12329687).

**Comment by furuihe** [comment]
@tony-- Somebody has created an issue in apache,but the issue is still Unassigned,does anybody maintain the plugin now?
https://issues.apache.org/jira/browse/CB-11423?jql=component%20%3D%20%22Plugin%20Screen%20Orientation%22%20AND%20project%20%3D%20CB

**Comment by tony--** [comment]
@furuihe - I'll take a look.
