### ISSUE TITLE
window.screen.unlockOrientation() is not unlocking the orientation in iOS 9.x

### ISSUE THREAD

**Issue by pamidipradeep** [gbenvenuti/cordova-plugin-screen-orientation#118]
unlockOrientation() works fine on Android, but it doesn't on iOS (the version I tried on is 9.3.2). The screen continues to be locked to the orientation it was set to using the lockOrientation().

**Comment by gylippus** [comment]
@pamidipradeep did you figure something out here? I'm having some issues.
