### ISSUE TITLE
Screen is cutting when changing portrait mode to landscape mode

### ISSUE THREAD

**Issue by fahadmalikpl** [gbenvenuti/cordova-plugin-screen-orientation#119]
We are experiencing  following issue
Screen is appearing like this in landscpae mode
![screen shot 2016-07-27 at 12 04 51 pm](https://cloud.githubusercontent.com/assets/17248413/17167134/44cd6698-5390-11e6-8197-54a5e514e6ca.png)
Please let us know about its solution.
Thanks

**Comment by tony--** [comment]
@fahadmalikpl thanks for the report.
This repository is no longer being maintained ([see README for more information](https://github.com/gbenvenuti/cordova-plugin-screen-orientation/blob/master/README.md)).
Please log an issue in [Apache Cordova JIRA for the "Plugin Screen Orientation" component](https://issues.apache.org/jira/browse/CB/component/12329687).
