### ISSUE TITLE
When user has screen rotation locked the viewport won't resize

### ISSUE THREAD

**Issue by mediamas** [gbenvenuti/cordova-plugin-screen-orientation#120]
Hi! I'm using your plugin, in Android works great but in IOS when the user has screen rotation locked using IOS general settings, the viewport doesn't fill the screen, it remains as it's in portrait when changing it to landscape. I have already tried all meta viewport settings and non3 of them works, the weired thing is that it was working, it was after using phonegap build (latest version) when I've got a warning telling me of deprecated pgp repositories and changing all my plugins to npm that it started to happen. Any advice will be very much appreciated.

Thanks a lot!

**Comment by tony--** [comment]
@mediamas, thanks for the report.
This repository is no longer being maintained (see README for more information).
Please log an issue in Apache Cordova JIRA for the "Plugin Screen Orientation" component.
