### ISSUE TITLE
lockOrientation + unlockOrientation called synchronously breaks rotation

### ISSUE THREAD

**Issue by jrencz** [gbenvenuti/cordova-plugin-screen-orientation#121]
Background:
In my app I'm using portrait lock for pretty much every view but I allow user to rotate on one view.
Then after user goes away from that one special view I'd like to enforce portrait back. That works.

I was playing around with the plugin and I found out that calling 

```js
window.screen.lockOrientation('portrait');
window.screen.unlockOrientation();
```

(just to enforce portrait but without preserving the lock) does not work.
It enforces portrait but rotation becomes permanently locked. Even when I call `window.screen.unlockOrientation();` long after that the orientation becomes locked.

On the other hand calling

```js

window.screen.lockOrientation('portrait');
window.setTimeout(function () {
  window.screen.unlockOrientation();
} );
```

works as expected: it enforces portrait and unlock rotation.

Best (and most meaningful) helper I came up with was:

```js
function rotateTo(orientation) {
  window.screen.lockOrientation(orientation); 
  window.addEventListener('orientationchange', function unlockOnOrientationChange(){
    window.screen.unlockOrientation();
    window.removeEventListener('orientationchange', unlockOnOrientationChange);
  });
}
```

(it waits until orientation change takes place and then it unlocks).

I was testing on ios 10.0.1
I presume the `window.screen.unlockOrientation` was dropped for some reason (maybe because previous action was taking place at the moment) but I can't explain myself why rotation becomes permanently broken.

I suggest that apart from fixing the permanent lock issue you may extend the `lockOrientation`: It may return a promise resolved after `orientationchange` event is fired (or it should take a callback).

**Comment by tony--** [comment]
@jrencz, thanks for the report.
This repository is no longer being maintained (see README for more information).
Please log an issue in Apache Cordova JIRA for the "Plugin Screen Orientation" component.
