### ISSUE TITLE
Webview Gets Cut around 2/3 or 1/3 of width

### ISSUE THREAD

**Issue by gitlovenotwar** [gbenvenuti/cordova-plugin-screen-orientation#122]
There's a bug with the orientation, sometimes the view(window) gets cut around 2/3 of its width or 1/3. Have anyone experience the same problem?

**Comment by hussainak** [comment]
yea same issue

**Comment by hussainak** [comment]
I should also point that it happends on iOS only, Android is fine

**Comment by hussainak** [comment]
I just noticed this on Readme.md

This repository is no longer maintained.

This plugin has been adopted as an Apache Cordova Core Plugin.

The new repository location is https://github.com/apache/cordova-plugin-screen-orientation.

Open Issues and Pull Requests have been resolved and closed or migrated to Apache JIRA.

Please submit new Pull Requests to the Apache repo.

Please log new issues in Apache JIRA.

**Comment by tony--** [comment]
@gitlovenotwar, thanks for the report.
As @hussainak noted, this repository is no longer being maintained (see README for more information).
Please log an issue in Apache Cordova JIRA for the "Plugin Screen Orientation" component.
