### ISSUE TITLE
PortraitUpsideDown orientation is not available on iOS 7/8 after installing the plugin

### ISSUE THREAD

**Issue by avoskresensky** [gbenvenuti/cordova-plugin-screen-orientation#37]
After adding this plugin to my project I'm suddenly not able to switch to PortraitUpsideDown mode.
All other orientation work, but not that one. Even if none of the APIs are called.

I traced the problem to window.shouldRotateToOrientation handler in the iOS specific javascript file.
The way it is written seems to always block the upside-down in 'unlocked' mode. I guess you either need to add an 'unlocked' value to orientationMap or add "180" to the 'default'.

My workaround currently is to override window.shouldRotateToOrientation altogether, which prevents me from ever going back to a locked mode.

**Comment by ehack** [comment]
I discovered the same issue. My workaround was adding "180" to the default option in orientationMap (like you mentioned).
