### ISSUE TITLE
incorrect window dimensions reported

### ISSUE THREAD

**Issue by deostroll** [gbenvenuti/cordova-plugin-screen-orientation#40]
I suppose this is a race condition issue.

On an android device (Samsung Galaxy Tab Note N7000) I've consumed this plugin. I have attempted to obtain window dimensions right after `screen.lockOrientation()` is called, and later in a `window.setTimeout()` callback. (All this in the same page). 

I have observed that they yielded different values.

What this plugin actually needs is a state which tells developers that its safe to obtain window dimensions. I think this discrepancy is due to the fact that the code has tried to access the window dimensions before the `WebView` has completed modifying the state of `window` object.

**Comment by SebT** [comment]
+1 I have the same problem here, even when listening to `onorientationchange`, the reported height and width are incorrect

**Comment by deostroll** [comment]
@SebT my first suggestion would be to change the device. Because this usually is an indication that something else is also broken or will break. (My experience). 

Otherwise, you can put the logic, to test if it is safe to take it, in a ```setInterval``` which fires repeatedly, until that test fails. 

```
var k =  {w: window.innerWidth, h: window.innerHeight }; //unsafe access
var callBack = function() {
    //its safe to access here.
   var d = {w: window.innerWidth, h: window.innerHeight };
};
var testAgain = true;
var tmr = setInterval(function(){
    if(testAgain) {
        testAgain = (k.w !== window.innerWidth);
        k.w = window.innerWidth;
    }
    else {
        //fire the callback
        callBack();
        clearInterval(tmr);
    }
}, 500);

**Comment by SebT** [comment]
@deostroll Yes I did something similar, here's the code:
```javascript
var preRotation = {w: window.innherWidth, h: window.innerHeight};
rotationCheck = setInterval(function () {
  if (preRotation.w !== window.innerWidth || preRotation.h !== window.innerHeight) {
    clearInterval(rotationCheck);
    callback(); // Orientation change done, do your thing
  }
}, 100);
```

**Comment by tony--** [comment]
@deostroll, @SebT - if I understand correctly, it sounds like the `orientationchange` event is fired before the orientation change is complete, resulting in the window dimensions being effectively stale at the time that the event is fired?  This sounds like a bug that would be worth looking into...

**Comment by tony--** [comment]
Migrated to Apache Cordova JIRA [CB-11356](https://issues.apache.org/jira/browse/CB-11356)
