### ISSUE TITLE
IOS rotation effect

### ISSUE THREAD

**Issue by mathieu94** [gbenvenuti/cordova-plugin-screen-orientation#41]
I use this plugin for changing orientation device and locking it. But the transition between landscape mode and portrait mode isn't good looking.

Is there a way to simulate the native rotation screen effect ? (particularly on Ipad IOS 8).

Thanks.

**Comment by jgladch** [comment]
Bump!

**Comment by derekcaneja** [comment]
Bump!

**Comment by gbenvenuti** [comment]
Unfortunately there is no control over the transition as iOS doesn't even support the ability to trigger a rotation in a view (this plugin is a hack).  I have looked into this before and have been unable to find a solution.  More than happy to accept pull requests or pointers to where others have addressed this issue.

**Comment by gbenvenuti** [comment]
I just had another look and it seems that iOS has changed the game again... It does look terrible now on 8.3, it was quite smooth on 8.0.  Will see what I can find.

**Comment by jgladch** [comment]
Any update here?

**Comment by chineseneo** [comment]
Hi, recently I was changing orientation to play video on page, and the view usually breaks. I'm using ios 9.2 on iphone 5c, any suggestion?

**Comment by vanseinfo** [comment]
1+

**Comment by tony--** [comment]
@mathieu94, @chineseneo - @gbenvenuti has released 1.4.2 which fixes some iOS issues. Unfortunately, I don't think this is going to address the "ugly orientation change" issue, but will you try 1.4.2 and provide an update, please?

**Comment by tony--** [comment]
Migrated to Apache Cordova JIRA [CB-11361](https://issues.apache.org/jira/browse/CB-11361)
