### ISSUE TITLE
THREAD WARNING: ['YoikScreenOrientation'] took '25.531006' ms. Plugin should use a background thread.

### ISSUE THREAD

**Issue by morkov4o** [gbenvenuti/cordova-plugin-screen-orientation#45]
How can we fix that? 

Thanks!

**Comment by gbenvenuti** [comment]
Hi @morkov4o 

Please provide a pull request if you would like this issue resolved.

**Comment by gbenvenuti** [comment]
Resolved in #54

**Comment by orlando-antonino** [comment]
I have submitted a fix to solve this problem , but it was ignored, could you integrate please?!!?

**Comment by gbenvenuti** [comment]
Hi @orlando-antonino,

As per comment above linking to #54 it is merged and in v1.4.0 release.
