### ISSUE TITLE
Whose view is not in the window hierarchy!

### ISSUE THREAD

**Issue by morkov4o** [gbenvenuti/cordova-plugin-screen-orientation#46]
when i try to make 

element.on("webkitbeginfullscreen", function() { 
console.log("webkitbeginfullscreen");
screen.lockOrientation('landscape-primary'); 
});

i`m getting 

Warning: Attempt to present <ForcedViewController: 0x16daaaa0> on <MainViewController: 0x155c2460> whose view is not in the window hierarchy!

any ideas?

**Comment by gbenvenuti** [comment]
Hi @morkov4o 

This plugin is based on an early version of the screen orientation api and does not support the fullscreen events.  What are you trying to achieve in your app? In cordova you should not need any of the fullscreen functions, the app is already fullscreen and if you want to hide the status bar you can use the statusbar plugin.

**Comment by morkov4o** [comment]
Hi,

thanks for the quick response. We have HTML5 video player and I want to force the full screen video to play in landscape mode. That`s why i`m using the screen orientation api.

**Comment by gbenvenuti** [comment]
Hi @morkov4o 

If you provide me with a working/failing test case then I can look into it further for you, iOS and screen orientation is a bit of a minefield.  It is achieved by presenting and removing a view over the top of the cordova view and has been broken in the past by ios updates.
