### ISSUE TITLE
Submit latest version to Phonegap Build

### ISSUE THREAD

**Issue by jemminger** [gbenvenuti/cordova-plugin-screen-orientation#58]
Phonegap Build only has v1.3.1 here:

  https://build.phonegap.com/plugins/1282

According to them, you need to submit an update?
  
  http://community.phonegap.com/nitobi/topics/submitting_new_version_of_3rd_party_plugin

**Comment by gbenvenuti** [comment]
Hi @jemminger,

You can install plugins directly from the cordova registry now so there should be no need to publish there.  (I am unable to publish as I don't have a phonegap account).

Here is a link to the phonegap announcement:

http://phonegap.com/blog/2014/12/09/phonegap-build-new-features/

**Comment by jemminger** [comment]
Great, thanks for the info!
