### ISSUE TITLE
[just a recommand] plugins.cordova.io will be deprecated in the near future

### ISSUE THREAD

**Issue by bau720123** [gbenvenuti/cordova-plugin-screen-orientation#59]
hi @gbenvenuti 

according to these
http://phonegap.com/blog/2015/05/26/npm-plugins-available/
http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

so...just want to inform you that your plugin should be move to npm in the future...

**Comment by gbenvenuti** [comment]
This was done about 2 weeks ago for this plugin.

**Comment by bau720123** [comment]
thanks @gbenvenuti 
got it
