### ISSUE TITLE
Plugin unsupported at PhoneGap Build

### ISSUE THREAD

**Issue by Deathspike** [gbenvenuti/cordova-plugin-screen-orientation#60]
I have a `config.xml` to use the latest Cordova CLI:

`<preference name="phonegap-version" value="cli-5.1.1" />`

And then:

`<gap:plugin name="cordova-plugin-screen-orientation" version="1.3.6" souce="npm" />`

Which results in `plugin unsupported: cordova-plugin-screen-orientation @ 1.3.6`. I suspect the issue comes from the fact that `plugin.xml` does not have 4.0.0 as a possible engine, but I'm not sure. Is there any way you can investigate this one?

//EDIT: Whoop, at least use `npm` as source. Still does not work though! Issue still valid.

**Comment by gbenvenuti** [comment]
Hi @Deathspike 

Sorry I haven't any experience with phonegap build.  Where there any error messages from build?

**Comment by gbenvenuti** [comment]
please reopen if issue persists.
