### ISSUE TITLE
screen is not function 

### ISSUE THREAD

**Issue by vinodhum** [gbenvenuti/cordova-plugin-screen-orientation#67]
screen.lockOrientation is not a function
installed the phonegap plugin but I still keep getting above error any idea what am I missing

**Comment by gbenvenuti** [comment]
Hi @vinodhum 

Did you run after `deviceready`?

**Comment by vinodhum** [comment]
yes I tried is all the different solutions out on google :)

.controller('PlayerCtrl', function($scope) {
document.addEventListener("deviceready", onDeviceReady, false);
    function onDeviceReady()
    {
        $scope.changeOriantationLandspace = function() {
            window.screen.lockOrientation('landscape');
        }
         
        $scope.changeOriantationPortrait = function() {
            window.screen.lockOrientation('portrait');
        }   
    }


});

tried it with out window but no luck

I also verified the plugin in is installed correctly but cant get it to work with ionic

**Comment by eirikrlee** [comment]
If you log the plugin object, you will see it only has Orientations array property, currOrientation string property, and a setOrientation method.  The documentation needs serious revision.

**Comment by vinodhum** [comment]
i tried that too 
 screen.setOrientation is not a function

**Comment by eirikrlee** [comment]
Do a console.log(screen) and see if you see undefined or an object.
If not, try cordova.plugins.screenorientation.setOrientation().  If that is undefined, do a console.log(cordova.plugins.screenorientation) and see its methods.

**Comment by vinodhum** [comment]
console.log(screen) give me long object and console.log(cordova.plugins.screenorientation) says undefined

**Comment by gbenvenuti** [comment]
@eirikrlee if you look at the code in screenorientation.js you will see that functions are actually added to the screen object (including lockOrientation) the cordova.plugins.screenorientation object is used for namespace only and is merged depending on the platform you are using you do not use it in your applications.  There is no issue with the documentation, the exposed api as added to the global screen object is as per documentation.

@vinodhum it looks as though the plugin is not installed correctly (or at all), i suggest trying to remove it and add it again.  
- What OS are you seeing this on (ios/android/both)? 
- What version of cordova? 
- What is the command you are using to install the plugin?

**Comment by vinodhum** [comment]
@gbenvenuti your correct it add api to screen and I verifed that plugin was install correctly I spent around 2 days to verify that plugin was installed correctly.
I am using it on ionic framework with phonegap developer app (tested on htc m8 with lollipop)

**Comment by gbenvenuti** [comment]
@vinodhum are you saying there is still an issue with `screen.lockOrientation`? if that is not a function then the plugin is not installed or available in javascript.  

Other thoughts:
* Have you added `cordova.js' to you html ?
* Are other plugins working correctly?

**Comment by joelcdoyle** [comment]
+1 

I have this exact same issue. Using: 
Cordova 5.3.3
Ionic 1.7.7

'cordova.js' is in the index.html
Other plugins are working currectly

plugins/fetch.json
```json
...
 },
    "cordova-plugin-screen-orientation": {
        "source": {
            "type": "registry",
            "id": "cordova-plugin-screen-orientation"
        },
        "is_top_level": true,
        "variables": {}
    }
}
```

plugins/ios.json
```json
{
    "prepare_queue": {
        "installed": [],
        "uninstalled": []
    },
    "config_munge": {
        "files": {
            "config.xml": {
                "parents": {
                    "/*": [
                        ...
                        {
                            "xml": "<feature name=\"YoikScreenOrientation\"><param name=\"ios-package\" value=\"YoikScreenOrientation\" /></feature>",
                            "count": 1
                        },
                        ...
                    ]
                }
            },
            "framework": {
                "parents": {
                    "AudioToolbox.framework": [
                        {
                            "xml": true,
                            "count": 1
                        }
                    ],
                    "CoreLocation.framework": [
                        {
                            "xml": false,
                            "count": 1
                        }
                    ],
                    "CoreGraphics.framework": [
                        {
                            "xml": false,
                            "count": 1
                        }
                    ]
                }
            },
            "*-Info.plist": {
                "parents": {
                    "NSLocationWhenInUseUsageDescription": [
                        {
                            "xml": "<string />",
                            "count": 1
                        }
                    ]
                }
            }
        }
    },
    "installed_plugins": {
       ...
        "cordova-plugin-screen-orientation": {
            "PACKAGE_NAME": "com.ionicframework.myapp276373"
        },
       ...
    },
    "dependent_plugins": {}
}
```

Main app.js
```js
.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
  })
})
```
Controller:
```js
.controller('MyCtrl', function($scope) {
  $scope.$on('$ionicView.beforeEnter', function(){
    screen.lockOrientation('portrait'); // lockOrientation is not defined
  });
});
```

The window.screen / screen object: 
```js
availHeight: 667
availLeft: 0
availTop: 0
availWidth: 375
colorDepth: 24
height: 667
orientation: ScreenOrientation
  angle: 0
  onchange: null
  type: "portrait-primary"
  __proto__: ScreenOrientation
pixelDepth: 24
width: 375
```

But lockOrientation is not defined, neither is unlockOrientation

**Comment by gbenvenuti** [comment]
Hi @joelcdoyle 

Can you confirm that the screenorientation.js & screenorientation.ios.js file are in the folder:

    platforms/ios/www/plugins/corddova-plugin-screen-orientation/www

And the source files are linked.  Open XCode, Plugins/YoikdScreenOrientation.m/h  select file then ensure there is a Checkbox Ticked for "Target Membership" in the right utilities panel.

I am unable to replicate this issue so will need your help tracking this down.

**Comment by joelcdoyle** [comment]
Thanks for the quick reply @gbenvenuti

Yes, those files exist in those folders.

In Xcode, "Target Membership" is checked for `Plugins/YoikScreenOreintation.m` but not for `Plugins/YoikScreenOrientation.h`

**Comment by gbenvenuti** [comment]
Hi @joelcdoyle 

The next step would be to see if the JS side of the plugin is actually running, how about putting in some logging (or debug) in around here:

https://github.com/gbenvenuti/cordova-plugin-screen-orientation/blob/master/www/screenorientation.js#L49

Let me know if it is actually attempting to add the functions to the screen object.

Finally is the rotate issue you are seeing similar to #1? If so maybe check out the meta viewport tags.

**Comment by joelcdoyle** [comment]
Here are my findings @gbenvenuti 

The problem is not he same os #1, but it is close. The screen still rotates, but the view is resized and the full width of the screen is used. 

Inside the plugin I added some log messages:
```js
function addScreenOrientationApi(screenObject) {
    console.log("Checking if lock or unlock already set");
    if (screenObject.unlockOrientation || screenObject.lockOrientation) {
        console.log("Lock or unlock already set, returning");
        return;
    }

    screenObject.lockOrientation = function(orientation) {
        if (Orientations.indexOf(orientation) == -1) {
            console.log('INVALID ORIENTATION', orientation);
            return;
        }
        screenOrientation.currOrientation = screenObject.orientation = orientation;
        screenOrientation.setOrientation(orientation);
    };

    screenObject.unlockOrientation = function() {
        screenOrientation.currOrientation = screenObject.orientation = 'unlocked';
        screenOrientation.setOrientation('unlocked');
    };

    console.log("screenObject.lockOrientation: " + screen.lockOrientation);
    console.log("screenObject.unlockOrientation: " + screen.unlockOrientation);
}
```

Also in my controller:

```js
.controller('LoginCtrl', function($scope) {
  console.log("Controller init, screen.lockOrientation: " + screen.lockOrientation); // <-- does not show up in log
  $scope.$on('$ionicView.beforeEnter', function(){
    console.log("Inside beforeEnter event, screen.lockOrientation: " + screen.lockOrientation); // <-- does not show up in log
    document.addEventListener("deviceready", onDeviceReady, false);
    function onDeviceReady()
    {
      console.log("Attempting to lock orientation, screen.lockOrientation: " + screen.lockOrientation); // <-- shows up in log
      screen.lockOrientation('portrait');
    }
  });
});
```

In the console: 

```
Oct 29 10:28:58 my-app[53277]: Checking screenObject for unlockOrientation and lockOrientation
Oct 29 10:28:58 my-app[53277]: screenObject.unlockOrientation: function () {
	        screenOrientation.currOrientation = screenObject.orientation = 'unlocked';
	        screenOrientation.setOrientation('unlocked');
	    }
Oct 29 10:28:58 my-app[53277]: screenObject.lockOrientation: function (orientation) {
	        if (Orientations.indexOf(orientation) == -1) {
	            console.log('INVALID ORIENTATION', orientation);
	            return;
	        }
	        screenOrientation.currOrientation = screenObject.orientation = orientation;
	        screenOrientation.setOrientation(orientation);
	    }
Oct 29 10:28:58 my-app[53277]: Attempting to lock orientation, screen.lockOrientation: function (orientation) {
               if (Orientations.indexOf(orientation) == -1) {
	            console.log('INVALID ORIENTATION', orientation);
	            return;
	        }
	        screenOrientation.currOrientation = screenObject.orientation = orientation;
	        screenOrientation.setOrientation(orientation);
	    }
```

So, it appears everything is getting loaded. And the function exists when it is called, but it does not prevent the screen from rotating. 

I see this message in the log when I rotate the device 180 degrees: 
```
Oct 29 10:56:22 assertiond[53822]: assertion failed: 15A284 13B137: assertiond + 12188 [93FFE0B6-5C27-387F-B32A-6EE378BBB22A]: 0x1
Oct 29 10:56:22 backboardd[53819]: CoreAnimation: failed to allocate 0 bytes
Oct 29 10:56:22 SpringBoard[53818]:  * bad fence setup * we're setting up a potentially deferrable transaction while we are already tracking an animation fence - this will probably cause us to blow the fence
Oct 29 10:56:22 assertiond[53822]: assertion failed: 15A284 13B137: assertiond + 12188 [93FFE0B6-5C27-387F-B32A-6EE378BBB22A]: 0x1
 ```

**Comment by dahei** [comment]
@joelcdoyle 

> I'm using Ionic View to load the app on my iOS 9.1 iPhone 5 and when I rotate my device [...]

http://docs.ionic.io/docs/view-usage

Ionic View isn't **your** cordova container and does **not** contain your cordova plugins. It's just a pre-build cordova app which simply loads your ionic app into the WebView. As I read the list of the pre-installed plugins, the screen orientation plugin is not installed. So it can't work in that environment.

Did you test your app building it with XCode and deploy it directly to your iPhone?

**Comment by joelcdoyle** [comment]
@dahei That could very well be the issue. I have also noticed that the status bar color is not correct when I run my app with Ionic View, and it is not in the list of supported plugins. Thanks for brining that to my attention.

**Comment by deepakrout** [comment]
I am having same issue. Were you able to figure out the problem?

**Comment by arielgelbard** [comment]
It wasn't working for me either but I figured it out (this is on android):

I added `  <script type="text/javascript" src="cordova.js"></script>
  <script type="text/javascript" src="plugins/cordova-plugin-screen-orientation/www/screenorientation.js"></script>` to my "index.html"

`screen.lockOrientation('portrait');`

**Comment by cegonzal91** [comment]
Hi, I have the same problem, I ran cordova plugin add cordova-plugin-screen-orientation and then I try to do all the things that are said before but it is impossible do it work....
Someone of before with the issue could do it work? I don't know what I'm doing wrong... I don't know if there is a possibility to upload a single example
Thanks!

**Comment by cegonzal91** [comment]
Or better, if someone can say me step by step how add and do it work please!

**Comment by drodrigo** [comment]
In my case a qucik workaround (but by far not the best solution) was to set a timeout (a second or so)

**Comment by tony--** [comment]
@vinodhum - is your original issue resolved?
@joelcdoyle - @gbenvenuti has released 1.4.2 which fixes some iOS issues. I'm not sure if it will address your specific issue, but will you try 1.4.2 and provide an update, please?

**Comment by vinodhum** [comment]
Thank you all issue was resolved using Android build, initially I was using Ionic view and it didn't work with that.

**Comment by JMoli** [comment]
The docs say screen.unlockOrientation() is the function to call but after inspecting the proto the actual call I had to use was screen.orientation.unlock(); incase anyone else comes across this problem.
