### ISSUE TITLE
Not working on AngularJs Cordova

### ISSUE THREAD

**Issue by marioaleogolsat** [gbenvenuti/cordova-plugin-screen-orientation#68]
I've been trying to use the plugin, but i can't make it work with Angulas.js + Cordova, I'm putting it inside a controller that's linked to the view by ui-router.

    'use strict';

    angular.module('ngapp').controller('LoginController', function(global, loginService, $state, $scope){
        var ctrl = this;
 
        $window.screen.lockOrientation('portrait');

        ctrl.msg = 'Usuario / Senha Invalido';
    
        ctrl.showMsg = false;
    
        ctrl.user = global.info.user || null;
    
        ctrl.passwd = null;
    
        ctrl.validate = function(){
            loginService.login({"key": global.info.key, "user": ctrl.user, "pass": ctrl.passwd, "tipo": 0})
            .success(function(data){
                if(data.value == -1 || data.value == 0){
                    document.getElementById('loginMsg').style.width = '170px';
                    ctrl.msg = 'Usuario / Senha Invalido';    
                    ctrl.showMsg = true;
                    ctrl.passwd = '';
                } else{
                    ctrl.showMsg = false;
                    global.info.cliID = data.objects[0].cliID;
                    global.info.usuID = data.objects[0].usuID;
                    global.info.seeCmd = data.objects[0].visualizaComandos;
                    global.info.user = ctrl.user;
                    ctrl.msg = 'Sucesso';
                    $state.go('main');
                }
            })
            .error(function(err){
                document.getElementById('loginMsg').style.width = '96px';
                ctrl.msg = 'Sem conexão';
                ctrl.showMsg = true;
                ctrl.passwd = '';
            });
        };
    });

It throws: $window.screen.lockOrientation is not a function.
I've already tried to call it inside a $scope.function and inside a default function.

This is the loading of the scripts:

        
        <script type="text/javascript" src="lib/lodash.min.js"></script>
        <script type="text/javascript" src="lib/angular.min.js"></script>
        <script type="text/javascript" src="lib/angular-simple-logger.min.js"></script>
        <script type="text/javascript" src="lib/angular-google-maps.min.js"></script>
        <script type="text/javascript" src="lib/angular-ui-router.min.js"></script>
        <script type="text/javascript" src="lib/angular-aria.min.js"></script>
        <script type="text/javascript" src="lib/angular-animate.min.js"></script>
        <script type="text/javascript" src="lib/angular-touch.min.js"></script>
        
        
        <script type="text/javascript" src="lib/angular-material-icons.min.js"></script>
        <script type="text/javascript" src="lib/angular-material.min.js"></script>
        
        
        <script type="text/javascript" src="lib/ng-cordova.min.js"></script>
        <script src="cordova.js"></script>
        
        
        
        
        
        <script type="text/javascript" src="lib/angular-uuid4.min.js"></script>
        <script type="text/javascript" src="lib/angular-uuid.js"></script>
        <script type="text/javascript" src="lib/jsonrpc.js"></script>
        <script type="text/javascript" src="lib/app.js"></script>
        
        
        <script type="text/javascript" src="lib/routes.js"></script>
        
        
        <script type="text/javascript" src="lib/google-maps.js"></script>
        <script type="text/javascript" src="lib/services/login-service.js"></script>
        <script type="text/javascript" src="lib/services/poi-service.js"></script>
        <script type="text/javascript" src="lib/services/info-service.js"></script>
        
        
        <script type="text/javascript" src="lib/controllers/app-controller.js"></script>
        <script type="text/javascript" src="lib/controllers/main-controller.js"></script>
        <script type="text/javascript" src="lib/controllers/login-controller.js"></script>

The device ready is in the app.js:

    'use strict';

    angular.module('ngapp', [ 'ngTouch', 'ui.router', 'uiGmapgoogle-maps', 'uuid4', 'angular-uuid', 'jsonrpc', 'ngMdIcons', 'ngMaterial', 'ngCordova' ])

    .run(function($rootScope){
        document.addEventListener("deviceready", function () {
            $cordovaPlugin.someFunction().then(success, error);
        }, false);
        if(window.StatusBar){
            StatusBar.overlaysWebView(false);
            StatusBar.backgroundColorByName("black");
        }
        $rootScope.$watch('window.StatusBar', function(newValue, oldValue) {
            StatusBar.overlaysWebView(false);
            StatusBar.backgroundColorByName("black");
        }); 
    });

Is there a version for ngCordova?
If not, how to properly call it in this case?

**Comment by gbenvenuti** [comment]
are you able to inspect (chrome/safari) and try and call it from the console?

    window.screen.lockOrientation('portrait');

If that doesn't work then the plugin is not installed correctly.

If it does then I would look at when your LoginController is being loaded (and ensure after device ready).  It has been a while since I have done angular but I would probably create a service for it with a device ready wrapper so you don't have to manage it in your controller code.

Finally the example is referencing $window, this is not passed in as an argument in your controller, so technically shouldn't work (could be wrong on this though).

**Comment by abcd-ca** [comment]
@marioaleogolsat I've got it working in an Ionic (AngularJS) project. I wasn't aware of the $window object so I'm using screen.foo not $window.screen.foo but that might not matter. What I think you're missing is the [deviceready](https://cordova.apache.org/docs/en/4.0.0/cordova_events_events.md.html#deviceready) wrapper that all cordova calls should have. Put the lockOrientation call inside a deviceready callback and I think you'll be set. I did notice fyi that you can't call unlockOrientation() prior to a lockOrientation() call so watch out for that.

**Comment by vinodhum** [comment]
@abcd-ca can you plz share demo on GitHub where you got screen orientation working with ionic 
I cant get mine work

Thank You

**Comment by marioaleogolsat** [comment]
You're right @abcd-ca, I've missed it, thanks.

**Comment by abcd-ca** [comment]
@vinodhum Assuming you've installed the plugin...

```
document.addEventListener("deviceready", function() {
  if (window.cordova) {
    if (myConfigUtil.isTablet) { //this is my own isTablet logic, use your own here
      console.log('app.js about to lock to landscape');
      return screen.lockOrientation('landscape');
    } else {
      return screen.lockOrientation('portrait');
    }
  }
});
```

Note, you can change orientations like,

`screen.lockOrientation('landscape');` then `screen.lockOrientation('portrait');` but heads up, I found out the hard way that doing, `screen.unlockOrientation()` prior to a `screen.lockOrientation(whateverOrientation)` call causes the `lockOrientation` call to fail.

**Comment by vinodhum** [comment]
I tried that too and it keeps saying screen.lockOrientation is not a function (don't know what am I doing wrong)
but when l list plugins I see its is installed
I tried removing and adding plugin
I am testing it on phonegap dev app using htc m8 

$ cordova plugin list
com.ionic.keyboard 1.0.4 "Keyboard"
cordova-plugin-console 1.0.1 "Console"
cordova-plugin-crosswalk-webview 1.3.1 "Crosswalk WebView Engine"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-screen-orientation 1.4.0 "Screen Orientation"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-statusbar 1.0.1 "StatusBar"
cordova-plugin-whitelist 1.0.0 "Whitelist"

**Comment by marioaleogolsat** [comment]
Some plugins doesn't work on emulation, try to build it on your device ou run it directly via usb

**Comment by vinodhum** [comment]
i testing it on phonegap dev app and ionc view app which is like running app on device
