### ISSUE TITLE
The notification seems to appear in the wrong orientation. 

### ISSUE THREAD

**Issue by smemane** [gbenvenuti/cordova-plugin-screen-orientation#70]
Even after applying the orientation, the app gets fixed to the orientation I apply, but the notification show up in the direction/orientation I am holding the ipad. For eg: I am applying portrait mode to my app, so it appears to be in portrait mode even when I am holding the ipad in landscape mode, but the email/any other app notifications show up along its height. Is this a known issue, or I am missing something?  Is there a way to fix this issue ?

**Comment by gbenvenuti** [comment]
Hi @smemane,

I'm not sure exactly what you're saying, can you please attach a screenshot?

**Comment by gbenvenuti** [comment]
please re-open if you have further information
