### ISSUE TITLE
Native video player (default iOS HTML5 video player) not respecting lockOrientation()

### ISSUE THREAD

**Issue by abcd-ca** [gbenvenuti/cordova-plugin-screen-orientation#71]
Hi, I've got lockOrientation working great (thanks!) but then I'm using a 3rd party HTML5 video player SDK which opens a video in the iOS default video player over top of my app and that player doesn't respect the orientation. When I tap Done in that player and it is dismissed, my HTML5 container is still correctly oriented and further calls to lockOrientation() work as expected. So, it seems that player is not governed by the the same ForcedViewController. Any ideas of how to handle this? I assume it's a native tweak that needs to be made.

**Comment by morkov4o** [comment]
same here, please help

**Comment by gbenvenuti** [comment]
This plugin has no control over 3rd party players (this plugin can only affect the main container/webview), perhaps there is an option in their api that allows for you to set the orientation when loading the player.

**Comment by abcd-ca** [comment]
@gbenvenuti Sorry, mentioning the 3rd party library I'm using probably created unnecessary confusion. The real issue isn't a 3rd party library API one – it's a default, native video player one. Regardless of the 3rd party library, if you open a video on iOS via HTML, I think the only way is for a native, default player to appear. Whatever your trigger is to start the video, you end up with the default iOS player. That's the player I'm curious about fixing the orientation. If you have insight into that API I'd be interested to know – I could help contribute to the native side of the plugin if you have a lead.

**Comment by gbenvenuti** [comment]
hi @abcd-ca if you can provide a simple html file showing the behaviour you described I can have a bit of a look for you.  I still don't believe that this is related to this plugin as this plugin only has control over the webview, which the video player is outside of.
