### ISSUE TITLE
Cordova screen orientation plugin, screen is flashing when changing orientation on iOS

### ISSUE THREAD

**Issue by shuyye** [gbenvenuti/cordova-plugin-screen-orientation#74]
I'm developing an app using Cordova/Ionic, and using the plugin for several different app screens.

On Android everything works just as fine, though while testing on iOS device (7.1), whenever I unlock the orientation to allow both landscape and portrait on a certain screen, and then going back to a screen that is fixed on portrait, it flashes quickly with a black screen for about 100ms during the 'orientation fix'.

I wonder if anyone encountered a similar situation before, that would be extremely helpful.

Much thanks!

**Comment by llw** [comment]
Is this problem solved?I met the same problem

**Comment by tony--** [comment]
@shuyye - @gbenvenuti has released 1.4.2 which fixes some iOS issues. Will you try 1.4.2 and provide an update, please?

**Comment by tony--** [comment]
No response in over a week and AFAIK this issue is resolved so I'm going to close this.
OP or other commenters - please provide additional feedback if this issue is not resolved for you.
