### ISSUE TITLE
cordova-plugin-screen-orientation not added in config.xml

### ISSUE THREAD

**Issue by spottuit** [gbenvenuti/cordova-plugin-screen-orientation#75]
After I fetched the plugin(>4) from NPM and I looked inside the config.xml I couldn't find a similar line like below for the plugin.
``<gap:plugin name="org.apache.cordova.media-capture" />``

I already tried guessing the plugin id/name:
``<gap:plugin name="org.apache.cordova.screen-orientation" />``
``<gap:plugin name="cordova-plugin-screen-orientation" />``
WIthout any luck because PhoneGap Build kept saying the plugin is unsupported.

Besides guessing I tried to find the plugin id/name on the sites below.
- https://build.phonegap.com/plugins
- http://plugins.telerik.com/cordova?start=0&search=screen-orientation&collection=plugins_telerik_cordova
- https://cordova.apache.org/plugins/

Can someone tell me the plugin id/name?

**EDIT:**
I have added the same question on stackoverflow:
http://stackoverflow.com/q/33563975/4815184

**Comment by bau720123** [comment]
well @spottuit 
https://www.npmjs.com/package/cordova-plugin-screen-orientation

you should use
```
<gap:plugin name="cordova-plugin-screen-orientation" source="npm" version="1.4.0" />
```

**Comment by spottuit** [comment]
Thanks :smiley:! PhoneGap Build recognises the plugin now, but the plugin doesn't work yet.
I get an error in the console:
``Uncaught TypeError: screen.lockOrientation is not a function(…)``

**Comment by bau720123** [comment]
hi @spottuit 
I have no this situation
Android or iOS
what version ?

**Comment by spottuit** [comment]
I am using a Nexus 5 with Android 6.0.
This is the code:
```javascript
   onDeviceReady: function() {
        app.receivedEvent('deviceready');
        screen.lockOrientation('landscape');
    }
```

**Comment by bau720123** [comment]
Android 6.0 ??!!!
I have no 6.0 system
too new...
sorry can't help you
maybe ask @gbenvenuti

**Comment by spottuit** [comment]
It works now for some reason I wish I knew why. Anyway thanks again for your help @bau720123.

**Comment by bau720123** [comment]
ok @spottuit 
good job
