### ISSUE TITLE
Question: orientationchange event returns empty object

### ISSUE THREAD

**Issue by MoPHL** [gbenvenuti/cordova-plugin-screen-orientation#76]
On android 4.4.4, with ionic and cordova 5.3.3 when using 
```
$ionicPlatform.ready(function () {
   window.addEventListener("orientationchange", function () {
     console.log('Orientation changed to ' + angular.toJson(screen.orientation));
   });
});
```
the console logs an empty object after the message: ``` Orientation changed to {} ```

So my question is, what am I doing incorrectly, or is there any incompatibility with the cordova version I'm using?

**Comment by arielgelbard** [comment]
try  console.log(screen.orientation.type); console.dir(screen.orientation);

**Comment by tony--** [comment]
@MoPHL - Is this still an issue? Can you try the latest release (1.4.2) of this plugin and provide an update?

**Comment by MoPHL** [comment]
@tony I have since dropped the use of this plugin in favour of the window.orientation property, since I just wanted to know the orientation type and didn't need any of the other functionalities, so I cannot confirm if it is currently working or not.
