### ISSUE TITLE
Portrait Orientation Lock not functioning on Samsung Galaxy Edge

### ISSUE THREAD

**Issue by JCummings01** [gbenvenuti/cordova-plugin-screen-orientation#79]
The plugin works in our app on the Nexus 6 running Marshmallow, but does not function on a Samsung Galaxy Edge 6.

**Comment by Joncom** [comment]
Cordova app with this plugin compiles OK for me as well (using http://cocoon.io), and `screen.lockOrientation` is defined, however calls such as `screen.lockOrientation('portrait');` and `screen.lockOrientation('landscape');` don't seem to do anything. Running on Samsung Galaxy S6.

**Comment by tony--** [comment]
@JCummings01 - I understand that the plugin works on Nexus 6 running Android 6 but not on a Samsung Galaxy Edge 6 - is the Edge device also running Marshmallow?  Do you have any more information on this issue?  Can you provide example steps to reproduce?

**Comment by tony--** [comment]
Migrated to Apache Cordova JIRA [CB-11358](https://issues.apache.org/jira/browse/CB-11358)
