### ISSUE TITLE
not working on cordova-ios@4.0.x (CDVShared.h is now gone)

### ISSUE THREAD

**Issue by oallouch** [gbenvenuti/cordova-plugin-screen-orientation#80]
Hi,

As you can see at https://github.com/apache/cordova-ios/tree/4.0.x/CordovaLib/Classes/Public , CDVShared.h isn't part of cordova-ios anymore.

Thx in advance,

Olivier Allouch
www.illicotravel.com

**Comment by Joncom** [comment]
Also having the same issue and cannot compile for iOS.
https://forums.cocoon.io/t/bug-report-orientation/778/6

**Comment by martindederer** [comment]
I stumbled upon this problem too. Removing the [include in question](https://github.com/gbenvenuti/cordova-plugin-screen-orientation/blob/master/src/ios/YoikScreenOrientation.h#L26) fixes the compile time error for me.

**Comment by Joncom** [comment]
@martindederer Does the plugin actually work though?

**Comment by gbenvenuti** [comment]
closing, see #84 for further discussion
