### ISSUE TITLE
lockOrientation does not seem to work consistently on OnePlus (One , Two) phones.

### ISSUE THREAD

**Issue by RobiFerentz** [gbenvenuti/cordova-plugin-screen-orientation#81]
Sometimes it works on these phones, sometimes it doesn't. Weird.

**Comment by tony--** [comment]
@RobiFerentz - Can you provide some more details about this issue?  What happens when it doesn't work?  Are there any errors in the log?

**Comment by tony--** [comment]
No response in over a week and not enough information to take action.
OP please provide additional feedback if this issue is not resolved for you.
