### ISSUE TITLE
screen.orientation already exists before plugin install and is NOT a string.

### ISSUE THREAD

**Issue by RobiFerentz** [gbenvenuti/cordova-plugin-screen-orientation#82]
The API mentions screen.orientation to be a string, but it is already set as an object before the plugin is even installed. The plugin does not override it, but it definitely is not a string.

**Comment by Moghul** [comment]
Same issue here, console.log(screen.orientation); prints an object, strangely even after deviceready.

**Comment by tony--** [comment]
@RobiFerentz - what platforms are you using?  The plugin only overrides screen.orientation after the orientation has changed at least once.  The current version of the plugin is based on an older spec - some browsers/platforms support a newer version of the spec where screen.orientation is an object (see #102).  The plan is for the 2.0.0 release of this plugin to switch to the newer spec.

If this feedback addresses your question, will you please close this issue?

**Comment by tony--** [comment]
No response in over a week and AFAIK this issue is resolved so I'm going to close this.
OP or other commenters - please provide additional feedback if this issue is not resolved for you.
