### ISSUE TITLE
Bug - not working with cordova-ios >= 4.0.1

### ISSUE THREAD

**Issue by JerryBels** [gbenvenuti/cordova-plugin-screen-orientation#84]
Hello,

I updated my cordova-ios in order to get some new functionnalities. The build process failed after that - 

>** BUILD FAILED **
>The following build commands failed:
>CompileC build/Myapp.build/Debug-iphonesimulator/Myapp.build/Objects->normal/i386/YoikScreenOrientation.o Myapp/Plugins/cordova-plugin-screen->orientation/YoikScreenOrientation.m normal i386 objective-c >com.apple.compilers.llvm.clang.1_0.compiler
>(1 failure)

I guess you will know better than me what has gone wrong...

Thanks ahead for help !

**Comment by Joncom** [comment]
What was the error message that occurred a little while before the snippet you posted?

**Comment by bau720123** [comment]
all detail right here
https://github.com/dpa99c/cordova-diagnostic-plugin/issues/27
this is why the error occur is

developer should be follow this in iOS@4.0.1
http://cordova.apache.org/announcements/2015/12/08/cordova-ios-4.0.0.html

**Comment by JerryBels** [comment]
Hey, thanks for answering,

Everything is followed on the official Cordova bug tracker. https://issues.apache.org/jira/browse/CB-10258

Anyway for now I got rid of the plugin and locked the orientation in config.xml.

Thanks

**Comment by Joncom** [comment]
Thanks for the link @JerryBels. I'll be sure to watch that issue.

**Comment by gbenvenuti** [comment]
HI all,

Sorry for not being on top of this, I have not had time to work on this plugin.  If you remove the `CDVShared.h` line it will compile but the plugin still does not work correctly in iOS 9.

In testing I was able to switch the orientation with the below, however have not been able to lock it to that orientation yet.

```objc
 [[UIDevice currentDevice] setValue:
     [NSNumber numberWithInteger: UIInterfaceOrientationLandscapeLeft]
                                forKey:@"orientation"];
```

I will continue to investigate as I have time but as always, pull requests welcome.

**Comment by bau720123** [comment]
really thanks @gbenvenuti reply
if anything good news，please let us know
Good Work !!!

**Comment by oallouch** [comment]
Hi @gbenvenuti ,
The Cordova team is going to make a core screen-orientation plugin, I think, based on your code.
You should get in touch with them.
https://issues.apache.org/jira/browse/CB-9528

thx in advance

Olivier Allouch
www.illicotravel.com

**Comment by bau720123** [comment]
awesome @oallouch 
hope one day the Cordova team will accomplish this job

**Comment by oallouch** [comment]
they said they'll start on february

**Comment by macfam** [comment]
I was able to use this version of the plugin with success on iOS 9: http://plugins.telerik.com/cordova/plugin/screenorientation

**Comment by markarupert** [comment]
Help this is critical to my project. I have to be able to lock the orientation for certain features of my app. 

Any idea from anyone how this can be fixed or if there is another plugin that could be used?

**Comment by tony--** [comment]
@JerryBels  - @gbenvenuti has released 1.4.2 which should fix this issue. Will you try 1.4.2 and provide an update, please?

**Comment by JerryBels** [comment]
@tony-- I'm sorry but I moved on to something else in my work, they left that project aside for now... Whenever I come back to it (which could be in months, really) I will definitely try again and if any input for me is relevant at this point I will submit it right away.

**Comment by tony--** [comment]
@JerryBels - no problem, thanks for the response.  @gbenvenuti I suggest this issue be closed unless someone else in the discussion disagrees.

**Comment by vin-ni** [comment]
yep

**Comment by tony--** [comment]
@markarupert - I suggest you try the latest release (1.4.2).

**Comment by markarupert** [comment]
@tony-- That did it. Thanks!

**Comment by ahaith** [comment]
I've found with 1.4.2 I am able to switch between portrait and landscape. However, when attempting to lock to landscape-primary or landscape-secondary, the device goes into general landscape mode which flips between primary and secondary.

**Comment by tony--** [comment]
@ahaith - yep, that is how it works right now.  We'll fix this when we update to the latest version of the spec.  Currently working on triaging all of the open issues, then we'll switch focus to the update which will be released as 2.0.0 (no timeline yet).

**Comment by rbarriuso** [comment]
v1.4.2 works on iPhone 5s with iOS 9.3.2

**Comment by tony--** [comment]
@rbarriuso - thanks for the confirmation, I'll close this as resolved.
OP or other commenters - please provide additional feedback if this issue is not resolved for you.
