### ISSUE TITLE
Ability to force changing the screen orientation?

### ISSUE THREAD

**Issue by jtomaszewski** [gbenvenuti/cordova-plugin-screen-orientation#85]
Currently we can lock/unlock the orientation mode. Is there however a possibility to **force** given orientation, that is change it in a given moment from portrait to landscape and viceversa?

Usage example: my whole app is being locked to a portrait-only mode; but on video pages I unlock the orientation mode, giving the users an opportunity to switch to landscape mode. However, after the user turns off the video, I'd want to go back to portrait mode, switching it to it right away the user closes the video app.

`screen.lockOrientation('portrait')` doesn't switch the orientation, if the current orientation is landscape.

Device I tested it on: iOS 8 (iphone6).

**Comment by Sachchida-Nand-Mishra** [comment]
I also have such type problem. But orientation is changing but after some time it goes back automatically and orientation is being unlocked.

Please anyone suggest me.

**Comment by Sachchida-Nand-Mishra** [comment]
screen.lockOrientation('portrait') works on only Android devices but not on iOS.

Please give a solution for it.

**Comment by tony--** [comment]
@jtomaszewski - @gbenvenuti has released 1.4.2 which fixes some iOS issues. Will you try 1.4.2 and provide an update, please?

**Comment by tony--** [comment]
No response in over a week and AFAIK this issue is resolved so I'm going to close this.
OP or other commenters - please provide additional feedback if this issue is not resolved for you.
