### ISSUE TITLE
No orientation with the inappbrowser

### ISSUE THREAD

**Issue by martinr77** [gbenvenuti/cordova-plugin-screen-orientation#87]
Hey,

The plugin works well with my local pages but inside of the inappbrowser the screen orientation is not working.

Is there a fix?

Best regards

**Comment by gbenvenuti** [comment]
Hi @martinr77 

inappbrowser does not have access to the cordova plugins, it is not possible to use this plugin inside an inappbrowser

**Comment by martinr77** [comment]
Hmmm but with Phonegap Build it works. Which plugin is there in use?

**Comment by tony--** [comment]
It seems like this issue is about an unsupported feature, should it be closed?

**Comment by tony--** [comment]
AFAIK this issue is about an unsupported feature.
OP please provide additional feedback if you believe additional action should be taken to address this issue.
