### ISSUE TITLE
Cordova 6.0.0 and CDVShare.h

### ISSUE THREAD

**Issue by sdbroscious** [gbenvenuti/cordova-plugin-screen-orientation#90]
Wanted to let you know that when I upgraded a project to Cordova 6.0.0 and went through the plugin upgrade process, I ran into a slight wrinkle: npm pulls cordova-plugin-screen-orientation 1.4.0 into the project but the resulting iOS platform wouldn't build because YoikScreenOrientation.h imports CDVShare.h, which is no longer in Cordova core. The only other version available via npm is 1.3.6.

I noticed that your master has a version of YoikScreenOrientation.h that doesn't rely on CDVShare.h so I pulled the plugin into the project via git. It appears to be working (on simulators, at least).

Upshot: Please consider releasing a version that doesn't rely on CDVShare.h. It'll save others a lot of time figuring out what's going on when they upgrade to Cordova 6.x.

**Comment by DanielDornhardt** [comment]
Hi, yes, I just noticed that too.

**Comment by gbenvenuti** [comment]
This fix has now been published to npm (1.4.1)

**Comment by DanielDornhardt** [comment]
Hi, thanks, great!

**Comment by sdbroscious** [comment]
thanks!
