### ISSUE TITLE
ios is not locking screen Phonegap Build using cli-6.0.0

### ISSUE THREAD

**Issue by jvwelzen** [gbenvenuti/cordova-plugin-screen-orientation#91]
Ios is not locking screen using phonegap build cli-6.0.0 cordova 4.0.1

**Comment by gbenvenuti** [comment]
hi @jvwelzen 

This is due to an API change in cordova 4.0.0

https://www.mail-archive.com/issues@cordova.apache.org/msg42847.html

Please also see conversation in #84 

I'll close this issue as they are related.
