### ISSUE TITLE
[Question] seem not work with iOS 9.2.1

### ISSUE THREAD

**Issue by bau720123** [gbenvenuti/cordova-plugin-screen-orientation#92]
hi @gbenvenuti 
I am using your 1.4.1 version from npm
well...I know Cordova team maybe have a plan to create a new "cordova-plugin-screen-orientation"
https://issues.apache.org/jira/browse/CB-9528

but for now I just want to ask you...
maybe your plugin "cordova-plugin-screen-orientation" in iOS 9.2.1 still have some issue，right ?
because in your sample code
https://github.com/gbenvenuti/cordova-plugin-screen-orientation#usage

in Android，everything looks great
in iOS 9.2.1，no crash but no any real affect...(in previous version that less than 9，work great too)

**Comment by gbenvenuti** [comment]
please see 2 other issues on this, #84 and #86

**Comment by bau720123** [comment]
OK OK
sorry for bother
