### ISSUE TITLE
Not working above iOS 8

### ISSUE THREAD

**Issue by edvenkat** [gbenvenuti/cordova-plugin-screen-orientation#93]
Hai friends...
I install the plugin to my project.but I try  to lock landscape mode it change to landscape again change to portrait immediately.i think it happend because of dismiss view controller line.please  tell me where I update the code .

**Comment by bau720123** [comment]
hi @edvenkat 
for now this plugin not work with iOS9 and above
https://github.com/gbenvenuti/cordova-plugin-screen-orientation/issues/84
see @gbenvenuti said

**Comment by edvenkat** [comment]
Any other option to lock the orientation.

**Comment by edvenkat** [comment]
Any idea guys..........?

**Comment by denisbabineau** [comment]
have a look at http://stackoverflow.com/questions/32684922/ios9-alternative-to-uidevice-currentdevice-setvalue-to-force-orientation for why this likely broke on IOS 9. It's unclear wether this will even be feasible going forward but at the very least would have your app require full screen.

**Comment by macfam** [comment]
I was able to use this functionality on iOS 9 using this version of the plugin: http://plugins.telerik.com/cordova/plugin/screenorientation

**Comment by denisbabineau** [comment]
@macfam can you elaborate on how the telerik fork resolves the screen lock not working on ios > 8 ? (or provide a working sample) Said fork is essentially an older version of this repo; I gave it a try with iOS 9.2.1 and cordova 6.0.0 and the lock functionality still didn't work. Furthermore, installing the telerik fork with cordova 6.0.0 actually results in the latest version of this repo's published version to be installed due to the renamer (due to telerik fork still using the old plugin id):

```
Notice: net.yoik.cordova.plugins.screenorientation has been automatically converted to cordova-plugin-screen-orientation and fetched from npm. This is due to our old plugins registry shutting down.
Fetching plugin "cordova-plugin-screen-orientation" via npm
```

I had to install manually from local source to test.

**Comment by macfam** [comment]
@denisbabineau here is my setup:

Using Cordova version 4.2.0 through the CLI (specific project requires the older version of Cordova)
Xcode 7.2.1
net.yoik.cordova.plugins.screenorientation 1.3.3.1 "Screen Orientation" (added from telerik)
Tested on an iOS 9.0.2 device and and iOS 9.3.1 device.

So it appears the older version of Cordova plus the older version of the plugin might be making the difference.

**Comment by gbenvenuti** [comment]
hi @macfam, yes the problem occurs when using cordova iOS > 4.0.1 as the shouldRotate function has been removed from cordova which is required for the current plugin implementation.  See #84 for further information.

**Comment by tony--** [comment]
@edvenkat - @gbenvenuti has released 1.4.2 which should fix this issue. Will you try 1.4.2 and provide an update, please?

**Comment by rbarriuso** [comment]
v1.4.2 works on iPhone 5s with iOS 9.3.2

**Comment by tony--** [comment]
@rbarriuso - thanks for the confirmation, I'll close this as resolved.
OP or other commenters - please provide additional feedback if this issue is not resolved for you.
