### ISSUE TITLE
screen.orientation => undefined

### ISSUE THREAD

**Issue by Kavian77** [gbenvenuti/cordova-plugin-screen-orientation#94]
Hi 
I'm using cordova 6 and screen orientation plugin ,
the event does well but when I ask for screen.orientation or window.screen.orientaion it returns undefined . 
I also tested : 
var s= Object.keys(screen); that's result is : 
availWidth , availHeight , availTop , availLeft , pixelDepth , colorDepth , width , height .
can You help me please ?

**Comment by Kavian77** [comment]
@lkounadis can you help me please ?

**Comment by lkounadis** [comment]
you will have to downgrade to 5.4.1 unfortunately cordova 6 doesnt seem to work well with screen-orientation

**Comment by Kavian77** [comment]
@lkounadis Hi
I have Downgraded cordova to v5.4.1 , created a project and it's android platform , built that and  successfully installed screen orientation plugin via : 
cordova plugin add cordova-plugin-screen-orientation
now when i use : 
window.addEventListener("orientationchange", function(){
    alert(screen.orientation);
});
it returns me undefined , wtf is my problem ? I'm really confused . Please help me again .
I'm using PhoneGap app on Windows to test it on my android.5 Phone

**Comment by lkounadis** [comment]
That is odd
can you do 
window.addEventListener("orientationchange", function(){
    console.log(screen); 
});

and see what objects are available?

**Comment by tony--** [comment]
@Kavian77 - Any update on this?  Is this still an issue with 1.4.2?

**Comment by Kavian77** [comment]
@tony-- hi Tony 
my Project has Failed because of Buffoonery of Phonegap
I will never use it again
Good Luck

**Comment by tony--** [comment]
@gbenvenuti - This should be closed.
