### ISSUE TITLE
Orientation detect at launch - always portrait

### ISSUE THREAD

**Issue by ajp8164** [gbenvenuti/cordova-plugin-screen-orientation#95]
When I launch my application in landscape mode the app is presented in portrait mode.

Config.xml has the following preference:
`<preference name="Orientation" value="default" />`

Changing the orientation works great after launch.  How can we set the application to launch in the correct orientation (if holding iPad in landscape, app should launch in landscape, not portrait).

**Comment by lkounadis** [comment]
I faced this problem recently, apparently I was using cordova 6 which doesnt play well with screen-orientation. I reverted back to 5.4.1 to get it to play again

**Comment by ajp8164** [comment]
Thanks for the reply!  We're using 5.4.1 as well.  It works in all cases except if holding the iPad landscape at launch the app comes up in portrait mode.  I can rotate the iPad and (after the device is ready) the presentation does rotate to landscape but it should come up in landscape to start with, right?

**Comment by lkounadis** [comment]
It seems to be working correctly on my project.
are you setting
screen.lockOrientation('landscape')
or
screen.unlockOrientation();

in the platform.ready ?

**Comment by ajp8164** [comment]
Not using lock/unlockOrientation() at all.  I'll have to revisit my startup to ensure I'm waiting for platform ready properly.  Thanks for your help!

**Comment by lkounadis** [comment]
;) hope this helps you then!

**Comment by tony--** [comment]
@ajp8164 - were you able to resolve this issue?  If so will you close it please?  If not will you provide an update?
