### ISSUE TITLE
It doesn't work with ionic 2!

### ISSUE THREAD

**Issue by MrBokeh** [gbenvenuti/cordova-plugin-screen-orientation#98]
It doesn't work with ionic 2!

**Comment by KoryNunn** [comment]
What issue are you seeing?

Can you provide a test-case?

**Comment by MrBokeh** [comment]
1) Using ionic 2 to create a tabs project
2) set root page to tabs
3) from tab page either set tabs to the new root page or use nav to push to the new page
`this.nav.push(NewPage);`
4) on the new page add the code as follow but the orientation just doesn't work at all with either cordova 5.4.1 and 6.1.0:
```
onPageWillEnter() {
    window.screen.lockOrientation('landscape');
  }
```

**Comment by KoryNunn** [comment]
This plugin has not been tested with ionic, and there are no plans to support it directly. However, if you supply code to investigate the issue, there is a chance it will be looked at.

I'd recommend you create a minimal application that exhibits this issue, put it on github, and link to it.

**Comment by MrBokeh** [comment]
will do

**Comment by MrBokeh** [comment]
Only a few steps as below to create the MVP and reproduce the problem, you will see the screen did turn landscape for 50ms and then change back:
Install ionic 2 (http://ionicframework.com/docs/v2/getting-started/installation/): 
`npm install -g ionic@beta`

Create a project (http://ionicframework.com/docs/v2/getting-started/tutorial/):
`ionic start MyIonic2Project tutorial --v2`

Add this plugin:
`ionic plugin add cordova-plugin-screen-orientation`

Add these code on any of the page:
```
onPageDidEnter() {
    screen.lockOrientation('landscape');
}
```

Run
`ionic build ios`
then this if you don't have an iPhone plugged in:
`ionic emulate ios`
or this if you have an iPhone plugged in:
`ionic run ios`

Here are some errors:
```
2016-04-09 09:35:25.803 MyIonic2Project[6269:1646296] -[WebActionDisablingCALayerDelegate willBeRemoved]: unrecognized selector sent to instance 0x125e66aa0
2016-04-09 09:35:25.803 MyIonic2Project[6269:1646296] *** WebKit discarded an uncaught exception in the webView:willRemoveScrollingLayer:withContentsLayer:forNode: delegate: <NSInvalidArgumentException> -[WebActionDisablingCALayerDelegate willBeRemoved]: unrecognized selector sent to instance 0x125e66aa0
```

**Comment by gbenvenuti** [comment]
Hi @MrBokeh,

If you are installing a fresh install of cordova you will likely get cordova iOS v4.0.x, there are a number of issues related to this already e.g #84.  You could try an install cordova iOS from the 3 branch and you may have more luck.  At this stage I have not had time to find a solution after cordova 4 removed the `shouldRotateToOrientation` call.

**Comment by MrBokeh** [comment]
Errr, lets flag this with Cordova if there's no workaround... I guess many people are using your plugin...

**Comment by tony--** [comment]
@MrBokeh - @gbenvenuti has released 1.4.2 which fixes some iOS issues. Will you try 1.4.2 and provide an update, please?

**Comment by tony--** [comment]
@MrBokeh - @gbenvenuti has released 1.4.2 which should has some fixes for iOS. Will you try 1.4.2 and provide an update, please?

**Comment by tony--** [comment]
Investigate Ionic support.

**Comment by tony--** [comment]
Migrated to Apache Cordova JIRA [CB-11359](https://issues.apache.org/jira/browse/CB-11359)
