### ISSUE TITLE
screen-orientation puts inappbrowser in background

### ISSUE THREAD

**Issue by lkounadis** [gbenvenuti/cordova-plugin-screen-orientation#99]
I have a problem when trying to use this plugin with inappbrowser plugin. 
The web app is originally set to portrait, and at some point I am trying to open an inAppBrowser and unlock the screen orientation.

I have tried to open and set using the code bellow, but both cases put the inAppBrowser to the background:

screen.unlockOrientation();
cordova.InAppBrowser.open(url, target, options);
OR
cordova.InAppBrowser.open(url, target, options);
screen.unlockOrientation();

The only way I have got it to work correctly is by setting the inappbrowser to open using a timeout:

screen.unlockOrientation();
setTimeout(function(){
cordova.InAppBrowser.open(url, target, options);
},100)

**Comment by tony--** [comment]
@lkounadis - Does this issue still occur with the latest release (1.4.2)?

**Comment by tony--** [comment]
@lkounadis - @gbenvenuti has released 1.4.2 which may fix this issue (unlockOrientation no longer alters the view hierarchy). Will you try 1.4.2 and provide an update, please?

**Comment by tony--** [comment]
Migrated to Apache Cordova JIRA [CB-11357](https://issues.apache.org/jira/browse/CB-11357)
